[tool.poetry]
name = "llm-notebook"
version = "0.1.0"
description = ""
authors = ["Renjith <renjith.baby@digicatapult.org.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = ">=1.25.1"
pandas = ">=2.0.3"
torch = ">=2.0.0"
torchaudio = ">=2.0.0"
torchvision = ">=0.15.0"
transformers = ">=4.31.0"
einops = ">=0.6.1"
accelerate = ">=0.21.0"
sentencepiece = "^0.1.99"
protobuf = "^4.24.2"


[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = ">=7.4.0"
pre-commit = ">=3.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
