name: Pre-commit Checks

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: Run Black
      run: pre-commit run black --all-files

    - name: Run Black-jupyter
      run: pre-commit run black-jupyter --all-files

    - name: Run Flake8
      run: pre-commit run flake8 --all-files

    - name: Run Isort
      run: pre-commit run isort --all-files

    - name: Run nbstripout
      run: pre-commit run nbstripout --all-files || echo "No notebooks for nbstripout"

    - name: Run Pydocstyle
      run: pre-commit run pydocstyle --all-files

    - name: Run Mypy
      run: pre-commit run mypy --all-files

    - name: Run Interrogate
      run: pre-commit run interrogate --all-files

    - name: Check for trailing whitespace
      run: pre-commit run trailing-whitespace --all-files

    - name: Check for EOF fixer
      run: pre-commit run end-of-file-fixer --all-files

    - name: Forbid new submodules
      run: pre-commit run forbid-new-submodules --all-files

    - name: Check added large files
      run: pre-commit run check-added-large-files --all-files

    - name: Check merge conflicts
      run: pre-commit run check-merge-conflict --all-files

    - name: Check case conflict
      run: pre-commit run check-case-conflict --all-files

    - name: Detect private key
      run: pre-commit run detect-private-key --all-files

    - name: Check safety
      run: pre-commit run python-safety-dependencies-check --all-files

    - name: Check security vulnerabilities
      run: pre-commit run bandit --all-files
